Se hacen las validaciones para administrador, con los métodos list, s…
COLMASH/COLMASH-CrossFitApp-BackEnd pull request #10
Opened 2021-06-30 21:26 UTC by NataliaBedoya

Se hacen las validaciones para administrador, con los métodos list, show, update, destroy, signup, sigin

2021-06-30 21:31 UTC, COLMASH approved these changes

2021-06-30 21:32 UTC, welfar approved these changes

2021-07-01 14:50 UTC, simonhoyos requested changes

2021-07-01 14:50 UTC, simonhoyos commented on src/controller/admin.controller.js
> +      console.log(error)
Borrar log

2021-07-01 14:50 UTC, simonhoyos commented on src/controller/user.controller.js
> +      console.log(user._id)
borrar log

2021-07-01 15:43 UTC, closed without merging