Admin 96
COLMASH/COLMASH-CrossFitApp-BackEnd pull request #22
Opened 2021-07-16 22:15 UTC by NataliaBedoya

2021-07-16 22:28 UTC, welfar requested changes

2021-07-16 22:28 UTC, welfar commented on src/controller/admin.controller.js
> +          dniType: admin.dniType,
falta el numero del dni

2021-07-17 00:30 UTC, COLMASH approved these changes

2021-07-17 19:58 UTC, NataliaBedoya commented on src/controller/admin.controller.js
> +          dniType: admin.dniType,
Corregido

2021-07-17 20:00 UTC, welfar approved these changes

2021-07-17 20:02 UTC, simonhoyos reviewed
De qué trata este PR? Cuál es la finalidad? Qué cambios se introdujeron? Empieza a agregarle descripciones a los PRe

2021-07-17 20:02 UTC, simonhoyos commented on src/controller/admin.controller.js
> +      console.log(adminId);
Borrar

2021-07-17 21:20 UTC, COLMASH approved these changes

2021-07-17 21:26 UTC, NataliaBedoya commented on src/controller/admin.controller.js
> +      console.log(adminId);
R!

2021-07-18 14:36 UTC, NataliaBedoya commented
> De qué trata este PR? Cuál es la finalidad? Qué cambios se introdujeron? Empieza a agregarle descripciones a los PRe

Se me pasó ponerle el título cuando lo cree.
Este pull request modifica las respuestas del back en administrador, usuario y coach para que envíe los datos de la persona que se está loggeando dejando de enviar el id y el password. De esta manera, acatamos la corrección previa sobre las tres peticiones continuas y  solo se hace una petición.

2021-07-18 14:57 UTC, simonhoyos approved these changes

2021-07-18 15:00 UTC, merged